src/routes/web.php
<?php

use App\Http\Controllers\Web\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [ProductController::class, 'index']);

Route::resource('product', ProductController::class);

src/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'sku',
        'description',
        'stock',
        'available'
    ];
}

src/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

src/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

src/app/Http/Controllers/Web/ProductController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Http\Requests\Web\StoreProductRequest;
use App\Models\Product;
use Illuminate\Http\JsonResponse;
use Illuminate\View\View;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $products = Product::paginate(10);
        $products->withPath('/product');

        return view('products.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('products.create');
    }

   /**
     * Store a newly created resource in storage.
     *
     * @param StoreProductRequest $request
     * @return JsonResponse
     */
    public function store(StoreProductRequest $request): JsonResponse
    {
        $validated = $request->validated();
        
        $product = new Product();
        $product->create($validated);

        return response()->json([
            'message'   => 'Created'
        ], 201);
    }

    /**
     * Show the detail page for resource.
     * 
     * @param Product $product
     * @return View
     */
    public function show(Product $product): View
    {
        return view('products.show', ['product' => $product]);
    }
}

src/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <title>Stocker | @yield('title')</title>
    @stack('head')
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/">{{ config('app.name') }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('product.create') }}">Create Product</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-5">
        @yield('content')
    </div>
    @stack('foot')
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>

src/resources/views/products/create.blade.php
@extends('layouts.app')
@section('title', 'Create Product')

@section('content')
    <div class="row">
        <div class="col">
            <h2>Create a Product</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div id="alertCreateProduct" role="alert"></div>
            <form id="createProductForm" action="{{ route('product.store') }}" method="POST">
                <meta name="csrf-token" content="{{ csrf_token() }}">
                <div class="mb-3">
                    <label for="name" class="form-label">Name:</label>
                    <input class="form-control" type="text" name="name" id="name">
                </div>
                <div class="mb-3">
                    <label for="sku" class="form-label">Sku:</label>
                    <input class="form-control" type="text" name="sku" id="sku">
                </div>
                <div class="mb-3">
                    <label for="description" class="form-label">Description:</label>
                    <input class="form-control" type="text" name="description" id="description">
                </div>
                <div class="mb-3">
                    <label for="stock" class="form-label">Stock:</label>
                    <input class="form-control" type="number" name="stock" id="stock">
                </div>
                <div class="mb-3">
                   <div class="form-check">
                       <input type="checkbox" class="form-check-input" id="hidden">
                       <label for="hidden" class="form-check-label">
                            Hidden
                       </label>
                   </div>
                </div>
                <div class="mb-3">
                    <button id="createProductBtn" class="btn btn-success">Create product</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('foot')
<script>
    document.getElementById("createProductForm").addEventListener('submit', handleCreateProduct);

    async function handleCreateProduct(event) {
        event.preventDefault();

        const token = document.querySelector('meta[name="csrf-token"]').content;
        const form = event.currentTarget;
        const url = form.action;
        const formData = new FormData(form);

        let alert = document.getElementById('alertCreateProduct');
        
        fetch(url, {
            headers: {
                "Accept": "application/json",
                "X-Requested-With": "XMLHttpRequest",
                "X-CSRF-TOKEN": token
            },
            method: 'POST',
            credentials: "same-origin",
            body: formData
        })
        .then((response) => response
        .json()
            .then((json) => ({
            ok: response.ok,
            status: response.status,
            body: json,
            }))
        )
        .then(({ ok, status, body }) => {
            if (!ok) {
                const message = getFormValidationMessage(status, body);
                throw new Error(message);
            }

            alert.className = 'alert alert-success';
            alert.innerHTML = body.message;
        })
        .catch(function(error) {
            alert.className = 'alert alert-danger';
            alert.innerHTML = error;
        });

        const getFormValidationMessage = (status, body) => {
            if (status !== 422) return "Something went wrong"; // Guard clause, Laravel throws a 422. Just set a default message
                let errorString = "";

            for (const [_, message] of Object.entries(body.errors)) {
                errorString += `<br />${message}`;
            }

            return errorString; // Make a pretty message in the format below
        };
    }
    
</script>
@endpush

src/resources/views/products/index.blade.php
@extends('layouts.app')
@section('title', 'Product Overview')

@section('content')
<div class="row">
    <div class="col">
        <h2>Product List</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="table-responsive-xl">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">SKU</th>
                        <th scope="col">Stock</th>
                        <th scope="col">Hidden</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($products as $product)
                        <tr scope="row">
                            <th scope="row">{{ $product->id }}</th>
                            <td>{{ $product->name }}</td>
                            <td>{{ $product->sku }}</td>
                            <td>{{ $product->stock }}</td>
                            <td>{{ $product->hidden === 0 ? 'no' : 'yes' }}</td>
                            <td>
                                <div class="row">
                                    <div class="col">
                                        <a class="btn btn-primary" href="{{ route('product.show', $product->id) }}" role="button">Details</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $products->links() }}
        </div>
    </div>
</div>
@endsection

src/resources/views/products/show.blade.php
@extends('layouts.app')
@section('title', 'Product Details')

@section('content')
<div class="row">
    <div class="col">
        <h2>Product Details</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-auto">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ $product->name }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Sku: {{ $product->sku }}</li>
                <li class="list-group-item">Stock: {{ $product->stock }}</li>
                <li class="list-group-item">Hidden: {{ $product->hidden === 0 ? 'no' : 'yes' }}</li>
            </ul>
            <div class="card-body">
                <a href="#" class="btn btn-warning">Update</a>
                <a href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header">Description:</div>
            <div class="card-body">
                <p>{{ $product->description }}</p>
            </div>
        </div>
    </div>
</div>
@endsection